"""Добавлен статус пользователей

Revision ID: 010
Revises: 009
Create Date: 2024-07-15 22:27:23.688930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from bot.db.models.users import Statuses

# revision identifiers, used by Alembic.
revision: str = '010'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_id_mapping')
    op.add_column('users', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(Statuses), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.create_table('file_id_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('short_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='file_id_mapping_pkey'),
    sa.UniqueConstraint('file_id', name='file_id_mapping_file_id_key'),
    sa.UniqueConstraint('short_id', name='file_id_mapping_short_id_key')
    )
    # ### end Alembic commands ###
