"""Добавлен статус пользователей 4

Revision ID: 013
Revises: 012
Create Date: 2024-07-16 00:34:53.637941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем тип ENUM в базе данных
    statuses = sa.Enum('active', 'not_authorized', 'banned', name='statuses')
    statuses.create(op.get_bind())

    # Изменяем столбец status с использованием выражения USING
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE statuses USING status::text::statuses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Обратно изменяем столбец status на VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE VARCHAR(255) USING status::text")

    # Удаляем тип ENUM из базы данных
    statuses = sa.Enum('active', 'not_authorized', 'banned', name='statuses')
    statuses.drop(op.get_bind())
    # ### end Alembic commands ###
